#!/usr/bin/env python
from Drac.EXEC import reduc
if __name__=='__main__':
	print '''
################################################
########## BEGINNING DRACULA REDUCTION #########
################################################
'''
	print "** REDUCTION **\n"
	reduc()
	print '\t[ok]\n'
	exit()
