#!/usr/bin/env python
from Drac.EXEC import do_quality
if __name__=='__main__':
	print '''
################################################
########## BEGINNING DRACULA QUALITY ###########
################################################
'''
	print "** QUALITY CHECK **\n"
	do_quality()
	print '\t[ok]\n'
	exit()
