#!/usr/bin/env python
if __name__=='__main__':
	print '''
################################################
########## BEGINNING DRACULA COMP ##############
################################################
'''
	from Drac.COMPARISON import run_comparison
	print "** BEGINNING COMPARRISSON **\n"
	run_comparison()
	print '\t[ok]\n'
	exit()
