#!/usr/bin/env python
if __name__=='__main__':
	print('''
################################################
########## BEGINNING DRACULA - SOM #############
################################################
''')
	from Drac.SOM import plot_som
	print "** PLOTTING SOM **\n"
	plot_som()
	print '\t[ok]\n'
	
	exit()
