#!/usr/bin/env python
from Drac.Main import do_quality
if __name__=='__main__':
	print '''
################################################
########## BEGINNING HMV PIPELINE ##############
################################################
'''
	print "** QUALITY CHECK **\n"
	do_quality()
	print '\t[ok]\n'
	exit()
