#!/usr/bin/env python
from Drac.EXEC import plot
if __name__=='__main__':
	print '''
################################################
########## BEGINNING HMV PIPELINE ##############
################################################
'''
	print "** PLOTTING **\n"
	plot()
	print '\t[ok]\n'
	exit()
