#!/usr/bin/env python
from Drac.EXEC import plot_spec
if __name__=='__main__':
	print '''
################################################
########## BEGINNING HMV PIPELINE ##############
################################################
'''
	print "** PLOTTING SPECS **\n"
	plot_spec()
	print '\t[ok]\n'
	exit()
