#!/usr/bin/env python
if __name__=='__main__':
	print('''
################################################
########## BEGINNING DRACULA - SOM #############
################################################
''')
	from Drac.SOM import run_som
	print "** RUNNING SOM **\n"
	run_som()
	print '\t[ok]\n'
	
	exit()
