#!/usr/bin/env python
from Drac.EXEC import cluster
if __name__=='__main__':
	print '''
################################################
########## BEGINNING DRACULA CLUSTERING ########
################################################
'''
	print "** CLUSTERING **\n"
	cluster()
	print '\t[ok]\n'
	exit()
