#!/usr/bin/env python
if __name__=='__main__':
	print '''
################################################
########## BEGINNING DRACULA COMP ##############
################################################
'''
	from Drac.COMPARISON import plot_comparison
	print "** PLOTTING COMPARRISSON **\n"
	plot_comparison()
	print '\t[ok]\n'

	exit()
