#!/usr/bin/env python
import sys
import os
sys.path.append(os.path.abspath(''))
from config_comparison import *
from plotting.plot_quality import plot_quality
def PRT_FMSG(msg_ok,msg_fail,FILE):
	if os.path.isfile(FILE) : print '\t*',msg_ok,'->',FILE
	else 			: print '\t*',msg_fail,'- no ',FILE,'file'
def PRT_FMSG_PLT(msg_ok,msg_fail,FILE):
	if FILE[-3:]=='pdf': PRT_FMSG(msg_ok,msg_fail,FILE)
	else:
		for Q in QUALITY_METHODS: PRT_FMSG(msg_ok,msg_fail,FILE[:-4]+'_'+Q+FILE[-4:])
if __name__=='__main__':
	print "** PLOTTING COMPARISON **\n"
	os.system('mkdir -p plots/')
	plot_quality(QUALITY_METHODS,'plots/quality'+PLOT_QUA_EXT)
	PRT_FMSG_PLT('QUALITY PLOT generated at','QUALITY PLOT not generated','plots/quality'+PLOT_QUA_EXT)
	print '\t[ok]\n'
	exit()
